enum SCREEN_NAMES {
    FAVORITE_SCREEN = 'FAVORITE_SCREEN',
    HOME_SCREEN = 'HOME_SCREEN',
    ITEM_CREATION_SCREEN = 'ITEM_CREATION_SCREEN',
    ITEM_SCREEN = 'ITEM_SCREEN',
    PROFILE_SCREEN = 'PROFILE_SCREEN',
    HOME_STACK = 'HOME_STACK',
};

export { SCREEN_NAMES };